# Generated by Django 4.2.20 on 2025-04-07 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodapp', '0007_cart'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AdminDetails',
        ),
    ]
